# Generated by Django 5.1.3 on 2025-01-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_uploadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlog',
            name='file_hash',
            field=models.CharField(default='default_hash', max_length=64),
            preserve_default=False,
        ),
    ]
