# Generated by Django 5.1.3 on 2025-01-19 23:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_uploadlog_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.invoicecomparison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
