# Generated by Django 5.1.3 on 2025-02-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_reminderschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivation_reason',
            field=models.CharField(choices=[('none', 'None'), ('user_request', 'User Request'), ('deletion_pending', 'Deletion Pending')], default='none', max_length=50),
        ),
    ]
