# Generated by Django 5.1.3 on 2024-12-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
