# Generated by Django 5.1.3 on 2024-11-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=150, unique=True)),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fullname', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('preferences', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voltix.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('provider', models.CharField(max_length=150)),
                ('file_path', models.CharField(max_length=255)),
                ('ocr_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('notification_setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ComparacionFacturas',
            fields=[
                ('comparison_id', models.AutoField(primary_key=True, serialize=False)),
                ('comparison_date', models.DateTimeField()),
                ('comparison_result', models.JSONField()),
                ('invoice1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_invoice1', to='voltix.factura')),
                ('invoice2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_invoice2', to='voltix.factura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='BaseMiLuz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('expected_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_kwh', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fixed_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_expected_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.usuario')),
            ],
        ),
    ]
