# Generated by Django 5.1.3 on 2024-11-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('provider', models.CharField(max_length=150)),
                ('file_path', models.CharField(max_length=255)),
                ('ocr_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=150, unique=True)),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='voltix.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('preferences', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='voltix.user')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('notification_setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.user')),
            ],
        ),
        migrations.CreateModel(
            name='MiLuzBase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('expected_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_kwh', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fixed_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_expected_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.user')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.user')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceComparison',
            fields=[
                ('comparison_id', models.AutoField(primary_key=True, serialize=False)),
                ('comparison_date', models.DateTimeField()),
                ('comparison_result', models.JSONField()),
                ('invoice1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_invoice1', to='voltix.invoice')),
                ('invoice2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_invoice2', to='voltix.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.user')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltix.user'),
        ),
    ]
