# Generated by Django 5.1.3 on 2024-12-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
